### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by Helos00111** [frikinjay/fractalportals#1]
I can't open minecraft with this mod, because it is crashing.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'FractalPortals' (fractalportals) 1.1.0 requires any version of fabric, which is missing!
	 - Mod 'Custom Portal Api' (customportalapi) 0.0.1-beta45-1.17 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Well, i installed Fabric after this, and this is what happend:

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config  for mod fractalportals
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config 
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource '' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

Fix it, pls

**Comment by frikinjay** [comment]
I dont need to fix it since its not the mod crashing but the lack of Fabric API which is needed by a lot of mods. You need to install [fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api).
